/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */

package org.mule.module.mongo.config;

import org.mule.MessageExchangePattern;
import org.mule.api.MuleContext;
import org.mule.api.MuleEvent;
import org.mule.api.MuleException;
import org.mule.api.MuleMessage;
import org.mule.api.MuleSession;
import org.mule.api.construct.FlowConstruct;
import org.mule.api.security.Credentials;
import org.mule.api.transformer.DataType;
import org.mule.api.transformer.TransformerException;
import org.mule.api.transport.ReplyToHandler;
import org.mule.construct.Flow;
import org.mule.management.stats.ProcessingTime;
import org.mule.module.mongo.api.MongoClient;
import org.mule.tck.junit4.FunctionalTestCase;

import java.io.OutputStream;
import java.net.URI;
import java.util.Set;

import org.junit.Test;
import org.mockito.Mockito;

/**
 * Namespace configuration test for the Connector
 *
 * @author flbulgarelli
 */
public class MongoConnectorWithMockMongoClientTestCase extends FunctionalTestCase {
    
    private static MongoClient client;

    @Override
    protected String getConfigResources() {
        return "mongo-namespace-with-client-mock-config.xml";
    }

    @Test
    public void testSendMessageToFlow() throws Exception {
        MuleEvent response = this.lookupFlowConstruct("ListCollections").process(getTestEvent(null));
        Mockito.verify(client.listCollections());
    }
    
    private Flow lookupFlowConstruct(String name) {
        return (Flow) muleContext.getRegistry().lookupFlowConstruct(name);
    }
    
    public static MongoClient createMockClient()
    {
        client = Mockito.mock(MongoClient.class);
        return client;
    }
}
